name: FTP Deploy

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Local root directory
        server-dir: /admin/ # Remote root directory
        git-ftp-args: --all
